/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RentalManagement;

import EmployeeAndCustomerManagement.Customer;
import EmployeeAndCustomerManagement.Employee;
import EmployeeAndCustomerManagement.Person;
import GUI.Utility.Utility;
import RentalRecordManagement.Rental;
import StockMaintenance.Car;
import StockMaintenance.CarStatus;
import StockMaintenance.Stock;
import StockMaintenance.Vehicles;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class RentCarIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RentCarIFrame
     */
    public RentCarIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentCarPanel = new javax.swing.JPanel();
        rentCarButton = new javax.swing.JButton();
        custIDLabel = new javax.swing.JLabel();
        custIDTextField = new javax.swing.JTextField();
        licenseNumLabel = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        licenseExpiryLabel = new javax.swing.JLabel();
        licenseExpiryTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        telephoneNumLabel = new javax.swing.JLabel();
        telephoneNumTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        empIDLabel = new javax.swing.JLabel();
        empIDTextField = new javax.swing.JTextField();
        rentCarIDLabel = new javax.swing.JLabel();
        rentCarIDTextField = new javax.swing.JTextField();
        rentDateLabel = new javax.swing.JLabel();
        rentDateTextField = new javax.swing.JTextField();
        returnDateLabel = new javax.swing.JLabel();
        returnDateTextField = new javax.swing.JTextField();

        rentCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rent A Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        rentCarPanel.setName("RentCar"); // NOI18N

        rentCarButton.setText("Rent Car");
        rentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarButtonActionPerformed(evt);
            }
        });

        custIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        custIDLabel.setText("Borrowers' ID");

        custIDTextField.setName("Customer ID"); // NOI18N
        custIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTextFieldActionPerformed(evt);
            }
        });

        licenseNumLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        licenseNumLabel.setText("License Number");

        licenseNumTextField.setName("License Number"); // NOI18N
        licenseNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumTextFieldActionPerformed(evt);
            }
        });

        licenseExpiryLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        licenseExpiryLabel.setText("License Expiry");

        licenseExpiryTextField.setName("License Expiry"); // NOI18N
        licenseExpiryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseExpiryTextFieldActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ageLabel.setText("Age");

        ageTextField.setName("Age"); // NOI18N
        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        dobLabel.setText("Date Of Birth");

        dobTextField.setName("Date Of Birth"); // NOI18N
        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addressLabel.setText("Address");

        addressTextField.setName("address "); // NOI18N
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        telephoneNumLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        telephoneNumLabel.setText("Telephone Number");

        telephoneNumTextField.setName("Telephone Number"); // NOI18N
        telephoneNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNumTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLabel.setText("Borrowers' Name");

        nameTextField.setName("Borrower's Name"); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        empIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        empIDLabel.setText("Employee ID");

        empIDTextField.setName("Employee ID"); // NOI18N
        empIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDTextFieldActionPerformed(evt);
            }
        });

        rentCarIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rentCarIDLabel.setText("Rented Car ID");

        rentCarIDTextField.setName("Rented Car ID"); // NOI18N
        rentCarIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarIDTextFieldActionPerformed(evt);
            }
        });

        rentDateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rentDateLabel.setText("Rent Date");

        rentDateTextField.setName("Rent Date"); // NOI18N
        rentDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentDateTextFieldActionPerformed(evt);
            }
        });

        returnDateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        returnDateLabel.setText("Return Date");

        returnDateTextField.setName("Return Date"); // NOI18N
        returnDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDateTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentCarPanelLayout = new javax.swing.GroupLayout(rentCarPanel);
        rentCarPanel.setLayout(rentCarPanelLayout);
        rentCarPanelLayout.setHorizontalGroup(
            rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentCarPanelLayout.createSequentialGroup()
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentCarPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rentCarPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(custIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(licenseNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(licenseExpiryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(licenseExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(telephoneNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telephoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentCarPanelLayout.createSequentialGroup()
                                .addComponent(empIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(empIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(rentCarIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(rentCarIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(rentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rentCarPanelLayout.createSequentialGroup()
                                .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        rentCarPanelLayout.setVerticalGroup(
            rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentCarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCarIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentCarIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseExpiryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarButtonActionPerformed
        // TODO add your handling code here:
        Hashtable<String,String> data = Utility.readData(rentCarPanel);

        String output= Utility.checkEmptyFields(data);

        if(output.length()!=0)
        {
            JOptionPane.showMessageDialog(this, output);
        }
        else
        {
            Stock st = MainFrame.stock;

            int customerID = Integer.parseInt(custIDTextField.getText());
            int employeeID = Integer.parseInt(empIDTextField.getText());
            int rentalID = Integer.parseInt(rentCarIDTextField.getText());
            String custName = nameTextField.getText();
            String licenseNum = licenseNumTextField.getText();
            String licenseExpiryString = licenseExpiryTextField.getText();
            int age = Integer.parseInt(ageTextField.getText());
            String dobString = dobTextField.getText();
            String address = addressTextField.getText();
            String telephoneNum = telephoneNumTextField.getText();
            String rentDateString = rentDateTextField.getText();
            String returnDueDateString = returnDateTextField.getText();

            //Parse Date
            DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
            Date dob = null;
            Date licenseExpiry = null;
            Date rentDate = null;
            Date returnDueDate = null;

            try {
                dob = df.parse(dobString);
                licenseExpiry = df.parse(licenseExpiryString);
                rentDate = df.parse(rentDateString);
                returnDueDate =df.parse(returnDueDateString);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            Customer cust = new Customer(licenseNum,age,licenseExpiry,customerID,custName,dob,address,telephoneNum);
            if(!(st.getCustomer().contains(cust)))
            {
                //Create new Customer entity if it does not exist
                st.getCustomer().add(cust);
            }

            //initialize variables to store values and create object of rental
            Person p;
            Rental rental = null;

            //filter customer object and check if customerID exists 
            p = st.getCustomer(customerID);
            if(p==null)
            {
                //filter Employee object and check if employeeID exists 
               p = st.getEmployee(employeeID); 
            }



            //iterate through all vehicles and get the one with matching carID
            for(Vehicles v : st.getStock())
            {
                Car car = (Car)v;
                if(car.getId() == rentalID && car.getStatus().toString().equals("AvailableForRent"))
                {//TODO - Validate if employeeID is in employee arrayList
                    //Set Car Status to RentedOut
                    rental = new Rental(p,car,rentDate,returnDueDate);
                    st.getRentalRecords().add(rental);
                    car.borrowed(rental);
                        for(Customer c : st.getCustomer())
                        {
                            if(c.getPersonID() == customerID)
                            {
                                c.borrowVehicle(rental,returnDueDate);
                            }
                        }
                    //add the same values to Car and customer arraylist in stock to add 
                    JOptionPane.showMessageDialog(this, "Car Successfully Rented!!");
                }
                else
                {
                    st.getCustomer().remove(cust);
                    JOptionPane.showMessageDialog(this, "Car Could not be added. Please contact the duty manager");
                }

            }
        } 
        
    }//GEN-LAST:event_rentCarButtonActionPerformed

    private void custIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTextFieldActionPerformed

    private void licenseNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumTextFieldActionPerformed

    private void licenseExpiryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseExpiryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseExpiryTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void telephoneNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNumTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void empIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDTextFieldActionPerformed

    private void rentCarIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentCarIDTextFieldActionPerformed

    private void rentDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentDateTextFieldActionPerformed

    private void returnDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDateTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel custIDLabel;
    private javax.swing.JTextField custIDTextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField empIDTextField;
    private javax.swing.JLabel licenseExpiryLabel;
    private javax.swing.JTextField licenseExpiryTextField;
    private javax.swing.JLabel licenseNumLabel;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton rentCarButton;
    private javax.swing.JLabel rentCarIDLabel;
    private javax.swing.JTextField rentCarIDTextField;
    private javax.swing.JPanel rentCarPanel;
    private javax.swing.JLabel rentDateLabel;
    private javax.swing.JTextField rentDateTextField;
    private javax.swing.JLabel returnDateLabel;
    private javax.swing.JTextField returnDateTextField;
    private javax.swing.JLabel telephoneNumLabel;
    private javax.swing.JTextField telephoneNumTextField;
    // End of variables declaration//GEN-END:variables
}
