/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RentalManagement;

import EmployeeAndCustomerManagement.Customer;
import GUI.Utility.Utility;
import RentalRecordManagement.Rental;
import StockMaintenance.Car;
import StockMaintenance.Stock;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class ReturnCarIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReturnCarIFrame
     */
    public ReturnCarIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnCarPanel = new javax.swing.JPanel();
        custIDLabel = new javax.swing.JLabel();
        empIDLabel = new javax.swing.JLabel();
        rentCarIDLabel = new javax.swing.JLabel();
        rentCarIDTextField = new javax.swing.JTextField();
        custIDTextField = new javax.swing.JTextField();
        empIDTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        returnDateLabel = new javax.swing.JLabel();
        returnDateTextField = new javax.swing.JTextField();
        rentCarButton = new javax.swing.JButton();

        returnCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        custIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        custIDLabel.setText("Borrowers' ID");

        empIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        empIDLabel.setText("Employee ID");

        rentCarIDLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rentCarIDLabel.setText("Rented Car ID");

        rentCarIDTextField.setName("Rented Car ID"); // NOI18N
        rentCarIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarIDTextFieldActionPerformed(evt);
            }
        });

        custIDTextField.setName("Customer ID"); // NOI18N
        custIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTextFieldActionPerformed(evt);
            }
        });

        empIDTextField.setName("EmployeeID"); // NOI18N
        empIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLabel.setText("Borrowers' Name");

        nameTextField.setName("Borrowers Name"); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        returnDateLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        returnDateLabel.setText("Return Date");

        returnDateTextField.setName("Return Date"); // NOI18N
        returnDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDateTextFieldActionPerformed(evt);
            }
        });

        rentCarButton.setText("Return Car");
        rentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnCarPanelLayout = new javax.swing.GroupLayout(returnCarPanel);
        returnCarPanel.setLayout(returnCarPanelLayout);
        returnCarPanelLayout.setHorizontalGroup(
            returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(returnCarPanelLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(returnCarPanelLayout.createSequentialGroup()
                            .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(returnCarPanelLayout.createSequentialGroup()
                            .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(custIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(returnCarPanelLayout.createSequentialGroup()
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnCarPanelLayout.createSequentialGroup()
                            .addComponent(empIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(empIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(returnCarPanelLayout.createSequentialGroup()
                            .addComponent(rentCarIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(rentCarIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        returnCarPanelLayout.setVerticalGroup(
            returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCarIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentCarIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentCarIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentCarIDTextFieldActionPerformed

    private void custIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTextFieldActionPerformed

    private void empIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void returnDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDateTextFieldActionPerformed

    private void rentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarButtonActionPerformed
        // TODO add your handling code here:
        Hashtable<String,String> data = Utility.readData(returnCarPanel);

        String output= Utility.checkEmptyFields(data);

        if(output.length()!=0)
        {
            JOptionPane.showMessageDialog(this, output);
        }
        else
        {
            Stock st = MainFrame.stock;

            int customerID = Integer.parseInt(custIDTextField.getText());
            int employeeID = Integer.parseInt(empIDTextField.getText());
            int rentalID = Integer.parseInt(rentCarIDTextField.getText());
            String custName = nameTextField.getText();
            String returnDateString = returnDateTextField.getText();

            //Parse Date
            DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
            Date returnDate = null;

            try {
                returnDate =df.parse(returnDateString);
            } catch (ParseException e) {
                e.printStackTrace();
            }


            for(Rental record : st.getRentalRecords())
            {
                if(record.getCar().getId() == rentalID)
                {
                    Car car = record.getCar();
                    car.returned();
                    for(Customer c : st.getCustomer())
                    {
                        if(c.getPersonID() == customerID)
                        {
                            c.returnVehicle(record);
                        }
                    }
                    
                    st.getRentalRecords().remove(record);
                    JOptionPane.showMessageDialog(this, "Car Successfully Returned!!");
                }

            }
        }
    }//GEN-LAST:event_rentCarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custIDLabel;
    private javax.swing.JTextField custIDTextField;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField empIDTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton rentCarButton;
    private javax.swing.JLabel rentCarIDLabel;
    private javax.swing.JTextField rentCarIDTextField;
    private javax.swing.JPanel returnCarPanel;
    private javax.swing.JLabel returnDateLabel;
    private javax.swing.JTextField returnDateTextField;
    // End of variables declaration//GEN-END:variables
}
