/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RentalManagement;

import RentalRecordManagement.Rental;
import StockMaintenance.Car;
import StockMaintenance.Stock;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class ShowCarFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowCarFrame
     */
    public ShowCarFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowCarPanel = new javax.swing.JPanel();
        customerIDLabel = new javax.swing.JLabel();
        customerIDTextField = new javax.swing.JTextField();
        startDateLabel = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        endDateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carsTable = new javax.swing.JTable();

        ShowCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Cars", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 24), new java.awt.Color(0, 204, 51))); // NOI18N

        customerIDLabel.setText("Customer ID");

        customerIDTextField.setName("Customer ID"); // NOI18N
        customerIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDTextFieldActionPerformed(evt);
            }
        });

        startDateLabel.setText("Start Date");

        startDateTextField.setName("Start Date"); // NOI18N

        endDateTextField.setName("End Date"); // NOI18N

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        endDateLabel.setText("End Date");

        carsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Make", "Model", "Colour", "Status", "Body Style", "Rent Per Day", "Registration Number"
            }
        ));
        jScrollPane1.setViewportView(carsTable);

        javax.swing.GroupLayout ShowCarPanelLayout = new javax.swing.GroupLayout(ShowCarPanel);
        ShowCarPanel.setLayout(ShowCarPanelLayout);
        ShowCarPanelLayout.setHorizontalGroup(
            ShowCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowCarPanelLayout.createSequentialGroup()
                .addGroup(ShowCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShowCarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE))
                    .addGroup(ShowCarPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(customerIDLabel)
                        .addGap(28, 28, 28)
                        .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(ShowCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShowCarPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ShowCarPanelLayout.createSequentialGroup()
                                .addComponent(startDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(endDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ShowCarPanelLayout.setVerticalGroup(
            ShowCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowCarPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ShowCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDLabel)
                    .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(ShowCarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Stock st = MainFrame.stock;
        
        int customerID = 0;
        String startDateString = null;
        String endDateString = null;
        Date startDate = null;
        Date endDate = null;
        Boolean process = false;
        
        if(!customerIDTextField.getText().equalsIgnoreCase(""))
        {
            customerID = Integer.parseInt(customerIDTextField.getText());
        }
        
        //Did not use the utility as it was messing with other code. instead used new Validation Code
        if(!startDateTextField.getText().equalsIgnoreCase("") && !endDateTextField.getText().equalsIgnoreCase(""))
        {
            startDateString = startDateTextField.getText();
            endDateString = endDateTextField.getText();
            
            DateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        try {
            startDate = df.parse(startDateString);
            endDate = df.parse(endDateString);
        } catch (ParseException e) {
            e.printStackTrace();
        }
            process = true;
        }

        //Getting access to the model of the bookTable model
        DefaultTableModel model = (DefaultTableModel)carsTable.getModel();
        //Freeing the model off the previous content
        model.setRowCount(0);
        //creating row with number of columns
        Object[] rows = new Object[7];
        //iterate through the list of cars to link with rows of table
        for(Rental record : st.getRentalRecords())
        {
            
            if(record.getBorrower().getPersonID() == customerID)
            {
                Car car = record.getCar();
                rows[0] = car.getMake();
                rows[1] = car.getModel();
                rows[2] = car.getColour();
                rows[3] = car.getStatus();
                rows[4] = car.getCarBodyType();
                rows[5] = car.getRentPerDay();
                rows[6] = car.getRegoNumber();
                model.addRow(rows);

                JOptionPane.showMessageDialog(this, "Showing Cars Matching by Customer ID");
            }
            if(process){
                if(record.getRentDate().compareTo(startDate) > 0  && record.getRentDueDate().compareTo(endDate) < 0)
                {
                    Car car = record.getCar();
                    rows[0] = car.getMake();
                    rows[1] = car.getModel();
                    rows[2] = car.getColour();
                    rows[3] = car.getStatus();
                    rows[4] = car.getCarBodyType();
                    rows[5] = car.getRentPerDay();
                    rows[6] = car.getRegoNumber();
                    model.addRow(rows);

                    JOptionPane.showMessageDialog(this, "Showing Cars Matching by Dates");
                }
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ShowCarPanel;
    private javax.swing.JTable carsTable;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    // End of variables declaration//GEN-END:variables
}
