/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qualitycars;


import GUI.HumanResource.AddEmployeeIFrame;
import GUI.HumanResource.DisplayInformationIFrame;
import GUI.HumanResource.UpdateInformationIFrame;
import GUI.RentalManagement.RentCarIFrame;
import GUI.RentalManagement.ReturnCarIFrame;
import GUI.RentalManagement.ShowCarFrame;
import GUI.StockManagement.AddCarIFrame;
import GUI.StockManagement.CarsAvailableIFrame;
import GUI.StockManagement.DisplayCarDetailsIFrame;
import GUI.StockManagement.UpdateCarInformationIFrame;
import StockMaintenance.Stock;


/**
 *
 * @author rbhaskar
 */
public class MainFrame extends javax.swing.JFrame {
static public Stock stock = new Stock();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        rentalManagementMenu = new javax.swing.JMenu();
        rentCarMenuItem = new javax.swing.JMenuItem();
        returnCarMenuItem = new javax.swing.JMenuItem();
        showCarMenuItem = new javax.swing.JMenuItem();
        humanResourceMenu = new javax.swing.JMenu();
        addNewEmployeeMenuItem = new javax.swing.JMenuItem();
        displayInfoMenuItem = new javax.swing.JMenuItem();
        updateInfoMenuItem = new javax.swing.JMenuItem();
        stockManagementMenu = new javax.swing.JMenu();
        addCarMenuItem = new javax.swing.JMenuItem();
        availablecarsMenuItem = new javax.swing.JMenuItem();
        displayCarDetailsMenuItem = new javax.swing.JMenuItem();
        updateCarInfoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 0, 0));

        rentalManagementMenu.setText("Rental Mangement");
        rentalManagementMenu.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        rentCarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.META_MASK));
        rentCarMenuItem.setText("Rent a Car");
        rentCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(rentCarMenuItem);

        returnCarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        returnCarMenuItem.setText("Return Car");
        returnCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(returnCarMenuItem);

        showCarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        showCarMenuItem.setText("Show Cars");
        showCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCarMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(showCarMenuItem);

        jMenuBar1.add(rentalManagementMenu);

        humanResourceMenu.setText("Human Resource");
        humanResourceMenu.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        addNewEmployeeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addNewEmployeeMenuItem.setText("Add New Employee");
        addNewEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmployeeMenuItemActionPerformed(evt);
            }
        });
        humanResourceMenu.add(addNewEmployeeMenuItem);

        displayInfoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        displayInfoMenuItem.setText("Display Information");
        displayInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayInfoMenuItemActionPerformed(evt);
            }
        });
        humanResourceMenu.add(displayInfoMenuItem);

        updateInfoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        updateInfoMenuItem.setText("Update Information");
        updateInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoMenuItemActionPerformed(evt);
            }
        });
        humanResourceMenu.add(updateInfoMenuItem);

        jMenuBar1.add(humanResourceMenu);

        stockManagementMenu.setText("Stock Management");
        stockManagementMenu.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        addCarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.META_MASK));
        addCarMenuItem.setText("Add Car");
        addCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(addCarMenuItem);

        availablecarsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.META_MASK));
        availablecarsMenuItem.setText("Cars Available");
        availablecarsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablecarsMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(availablecarsMenuItem);

        displayCarDetailsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.META_MASK));
        displayCarDetailsMenuItem.setText("Display Car Details");
        displayCarDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCarDetailsMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(displayCarDetailsMenuItem);

        updateCarInfoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.META_MASK));
        updateCarInfoMenuItem.setText("Update Car Information");
        updateCarInfoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarInfoMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(updateCarInfoMenuItem);

        jMenuBar1.add(stockManagementMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        ReturnCarIFrame frame = new ReturnCarIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_returnCarMenuItemActionPerformed

    private void updateInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        UpdateInformationIFrame frame = new UpdateInformationIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_updateInfoMenuItemActionPerformed

    private void addCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        AddCarIFrame frame = new AddCarIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_addCarMenuItemActionPerformed

    private void displayCarDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCarDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        DisplayCarDetailsIFrame frame = new DisplayCarDetailsIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_displayCarDetailsMenuItemActionPerformed

    private void updateCarInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarInfoMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        UpdateCarInformationIFrame frame = new UpdateCarInformationIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_updateCarInfoMenuItemActionPerformed

    private void availablecarsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablecarsMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        CarsAvailableIFrame frame = new CarsAvailableIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_availablecarsMenuItemActionPerformed

    private void addNewEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmployeeMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        AddEmployeeIFrame frame = new AddEmployeeIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_addNewEmployeeMenuItemActionPerformed

    private void displayInfoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayInfoMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        DisplayInformationIFrame frame = new DisplayInformationIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_displayInfoMenuItemActionPerformed

    private void rentCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        RentCarIFrame frame = new RentCarIFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_rentCarMenuItemActionPerformed

    private void showCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCarMenuItemActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        ShowCarFrame frame = new ShowCarFrame();
        MainPanel.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_showCarMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainPanel;
    private javax.swing.JMenuItem addCarMenuItem;
    private javax.swing.JMenuItem addNewEmployeeMenuItem;
    private javax.swing.JMenuItem availablecarsMenuItem;
    private javax.swing.JMenuItem displayCarDetailsMenuItem;
    private javax.swing.JMenuItem displayInfoMenuItem;
    private javax.swing.JMenu humanResourceMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem rentCarMenuItem;
    private javax.swing.JMenu rentalManagementMenu;
    private javax.swing.JMenuItem returnCarMenuItem;
    private javax.swing.JMenuItem showCarMenuItem;
    private javax.swing.JMenu stockManagementMenu;
    private javax.swing.JMenuItem updateCarInfoMenuItem;
    private javax.swing.JMenuItem updateInfoMenuItem;
    // End of variables declaration//GEN-END:variables
}
