/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.StockManagement;

import EmployeeAndCustomerManagement.Employee;
import StockMaintenance.Car;
import StockMaintenance.CarStatus;
import StockMaintenance.Stock;
import StockMaintenance.Vehicles;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class CarsAvailableIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CarsAvailableIFrame
     */
    public CarsAvailableIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availableCarPanel = new javax.swing.JPanel();
        showButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableCarsTable = new javax.swing.JTable();

        setClosable(true);

        availableCarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Available Cars", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        showButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        showButton.setText("Show Available Cars");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        availableCarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Make", "Model", "Manufacture Year", "Colour", "Status", "Body Type", "Renewal Rego", "Renewal WOF"
            }
        ));
        jScrollPane1.setViewportView(availableCarsTable);

        javax.swing.GroupLayout availableCarPanelLayout = new javax.swing.GroupLayout(availableCarPanel);
        availableCarPanel.setLayout(availableCarPanelLayout);
        availableCarPanelLayout.setHorizontalGroup(
            availableCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(availableCarPanelLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        availableCarPanelLayout.setVerticalGroup(
            availableCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableCarPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availableCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availableCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        Stock st = MainFrame.stock;
        
        //Getting access to the model of the bookTable model
        DefaultTableModel model = (DefaultTableModel)availableCarsTable.getModel();
        //Freeing the model off the previous content
        model.setRowCount(0);
        //creating row with number of columns
        Object[] rows = new Object[9];
        //iterate through the list of cars to link with rows of table
        for(Vehicles stock : st.getStock())
        {
            Car car = (Car)stock;
            if(stock instanceof Car && car.getStatus().equals(CarStatus.AvailableForRent))
            {
                rows[0] = car.getId();
                rows[1] = car.getMake();
                rows[2] = car.getModel();
                rows[3] = car.getYearOfManufacture();
                rows[4] = car.getColour();
                rows[5] = car.getStatus();
                rows[6] = car.getCarBodyType();
                rows[7] = car.getRegoRenew();
                rows[8] = car.getWOFdue();
                model.addRow(rows);
            }
        }
        JOptionPane.showMessageDialog(this, "Showing All Available Cars");
    }//GEN-LAST:event_showButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel availableCarPanel;
    private javax.swing.JTable availableCarsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showButton;
    // End of variables declaration//GEN-END:variables
}
