/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.StockManagement;

import GUI.Utility.Utility;
import StockMaintenance.Car;
import StockMaintenance.Stock;
import StockMaintenance.Vehicles;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class DisplayCarDetailsIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DisplayCarDetailsIFrame
     */
    public DisplayCarDetailsIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayCarDetailsPanel = new javax.swing.JPanel();
        regoNumberLabel = new javax.swing.JLabel();
        regoNumberTextField = new javax.swing.JTextField();
        manufactureYearLabel = new javax.swing.JLabel();
        manufactureYearTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        carsTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();

        DisplayCarDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Car Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        regoNumberLabel.setText("Registration Number");

        regoNumberTextField.setName("Rego Number"); // NOI18N
        regoNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regoNumberTextFieldActionPerformed(evt);
            }
        });

        manufactureYearLabel.setText("Manufacture Year");

        manufactureYearTextField.setName("Manufacture Year"); // NOI18N

        carsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Make", "Model", "Colour", "Status", "Body Style", "Rent Per Day", "Registration Number"
            }
        ));
        jScrollPane1.setViewportView(carsTable);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DisplayCarDetailsPanelLayout = new javax.swing.GroupLayout(DisplayCarDetailsPanel);
        DisplayCarDetailsPanel.setLayout(DisplayCarDetailsPanelLayout);
        DisplayCarDetailsPanelLayout.setHorizontalGroup(
            DisplayCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayCarDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayCarDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayCarDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 109, Short.MAX_VALUE)
                        .addComponent(regoNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regoNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(manufactureYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manufactureYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(DisplayCarDetailsPanelLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DisplayCarDetailsPanelLayout.setVerticalGroup(
            DisplayCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayCarDetailsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(DisplayCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regoNumberLabel)
                    .addComponent(regoNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufactureYearLabel)
                    .addComponent(manufactureYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayCarDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayCarDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regoNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regoNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regoNumberTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        int manufactureYear = 0;
        int regoNumber = 0;
        
        Stock st = MainFrame.stock;
        if(!manufactureYearTextField.getText().equalsIgnoreCase(""))
        {
            manufactureYear = Integer.parseInt(manufactureYearTextField.getText());
        }
        if(!regoNumberTextField.getText().equalsIgnoreCase(""))
        {
            regoNumber = Integer.parseInt(regoNumberTextField.getText());
        }
        
        //Getting access to the model of the bookTable model
        DefaultTableModel model = (DefaultTableModel)carsTable.getModel();
        //Freeing the model off the previous content
        model.setRowCount(0);
        //creating row with number of columns
        Object[] rows = new Object[7];
        //iterate through the list of cars to link with rows of table
        for(Vehicles stock : st.getStock())
        {
            Car car = (Car)stock;
            if(car.getYearOfManufacture() == manufactureYear)
            {
                rows[0] = car.getMake();
                rows[1] = car.getModel();
                rows[2] = car.getColour();
                rows[3] = car.getStatus();
                rows[4] = car.getCarBodyType();
                rows[5] = car.getRentPerDay();
                rows[6] = car.getRegoNumber();
                model.addRow(rows);

               JOptionPane.showMessageDialog(this, "Showing Car Matching by Manufacture Year");
            } 
            
            if(car.getRegoNumber() == regoNumber && car.getYearOfManufacture() != manufactureYear)
            {
                rows[0] = car.getMake();
                rows[1] = car.getModel();
                rows[2] = car.getColour();
                rows[3] = car.getStatus();
                rows[4] = car.getCarBodyType();
                rows[5] = car.getRentPerDay();
                rows[6] = car.getRegoNumber();
                model.addRow(rows);
                
                JOptionPane.showMessageDialog(this, "Showing Car Matching by Registration Number");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisplayCarDetailsPanel;
    private javax.swing.JTable carsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manufactureYearLabel;
    private javax.swing.JTextField manufactureYearTextField;
    private javax.swing.JLabel regoNumberLabel;
    private javax.swing.JTextField regoNumberTextField;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
