/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.StockManagement;

import EmployeeAndCustomerManagement.Employee;
import GUI.Utility.Utility;
import StockMaintenance.Car;
import StockMaintenance.CarStatus;
import StockMaintenance.CarTransmission;
import StockMaintenance.Stock;
import StockMaintenance.Vehicles;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import qualitycars.MainFrame;
import static qualitycars.MainFrame.stock;

/**
 *
 * @author rbhaskar
 */
public class UpdateCarInformationIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateCarInformationIFrame
     */
    public UpdateCarInformationIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateCarDetailsPanel = new javax.swing.JPanel();
        regoNumberLabel = new javax.swing.JLabel();
        regoNumberTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        colourLabel = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        transmissionLabel = new javax.swing.JLabel();
        rentPerDayLabel = new javax.swing.JLabel();
        rentPerDayTextField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        regoNumTextField = new javax.swing.JTextField();
        regoNumLabel = new javax.swing.JLabel();
        engineSizeTextField = new javax.swing.JTextField();
        engineSizeLabel = new javax.swing.JLabel();
        wofRenewLabel = new javax.swing.JLabel();
        wofRenewTextField = new javax.swing.JTextField();
        regoRenewLabel = new javax.swing.JLabel();
        regoRenewTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        transmissionComboBox = new javax.swing.JComboBox<>();
        statusComboBox = new javax.swing.JComboBox<>();
        employeeIDLabel = new javax.swing.JLabel();
        employeeIDTextField = new javax.swing.JTextField();

        setClosable(true);

        updateCarDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Car Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        regoNumberLabel.setText("Registration Number");

        regoNumberTextField.setName("regoNumber"); // NOI18N
        regoNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regoNumberTextFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search Car");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        colourLabel.setText("Colour");

        colourTextField.setName("colour"); // NOI18N
        colourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourTextFieldActionPerformed(evt);
            }
        });

        transmissionLabel.setText("Transmission");

        rentPerDayLabel.setText("Rent Per Day");

        rentPerDayTextField.setName("Rent Per Day"); // NOI18N
        rentPerDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextFieldActionPerformed(evt);
            }
        });

        statusLabel.setText("Status");

        regoNumTextField.setName("Rego Number"); // NOI18N
        regoNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regoNumTextFieldActionPerformed(evt);
            }
        });

        regoNumLabel.setText("Registration Number");

        engineSizeTextField.setName("Engine Size"); // NOI18N
        engineSizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineSizeTextFieldActionPerformed(evt);
            }
        });

        engineSizeLabel.setText("Engine Size");

        wofRenewLabel.setText("WOF Renew");

        wofRenewTextField.setName("WOF Renew"); // NOI18N
        wofRenewTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wofRenewTextFieldActionPerformed(evt);
            }
        });

        regoRenewLabel.setText("Rego Renew");

        regoRenewTextField.setName("Rego Renew"); // NOI18N
        regoRenewTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regoRenewTextFieldActionPerformed(evt);
            }
        });

        updateButton.setText("Update Car Details");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        transmissionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic", "Triptronic" }));
        transmissionComboBox.setName("transmission"); // NOI18N
        transmissionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmissionComboBoxActionPerformed(evt);
            }
        });

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AvailableForRent", "RentedOut", "UnderMaintenance" }));
        statusComboBox.setName("Status"); // NOI18N

        employeeIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        employeeIDLabel.setText("Employee ID");

        employeeIDTextField.setName("employeeID"); // NOI18N

        javax.swing.GroupLayout updateCarDetailsPanelLayout = new javax.swing.GroupLayout(updateCarDetailsPanel);
        updateCarDetailsPanel.setLayout(updateCarDetailsPanelLayout);
        updateCarDetailsPanelLayout.setHorizontalGroup(
            updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regoNumLabel)
                            .addComponent(statusLabel)
                            .addComponent(regoRenewLabel)
                            .addComponent(wofRenewLabel)
                            .addComponent(engineSizeLabel)
                            .addComponent(rentPerDayLabel)
                            .addComponent(transmissionLabel)
                            .addComponent(colourLabel))
                        .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(regoNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(colourTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(wofRenewTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(engineSizeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(rentPerDayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(regoRenewTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(transmissionComboBox, 0, 1, Short.MAX_VALUE)
                                    .addComponent(statusComboBox, 0, 1, Short.MAX_VALUE)))))
                    .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateCarDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                        .addComponent(regoNumberLabel)
                        .addGap(16, 16, 16)
                        .addComponent(regoNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(employeeIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        updateCarDetailsPanelLayout.setVerticalGroup(
            updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCarDetailsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regoNumberLabel)
                    .addComponent(regoNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(47, 47, 47)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourLabel)
                    .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transmissionLabel)
                    .addComponent(transmissionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDayLabel)
                    .addComponent(rentPerDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineSizeLabel)
                    .addComponent(engineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wofRenewLabel)
                    .addComponent(wofRenewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regoRenewLabel)
                    .addComponent(regoRenewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCarDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regoNumLabel)
                    .addComponent(regoNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateCarDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateCarDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regoNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regoNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regoNumberTextFieldActionPerformed

    private void colourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourTextFieldActionPerformed

    private void rentPerDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextFieldActionPerformed

    private void regoNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regoNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regoNumTextFieldActionPerformed

    private void engineSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineSizeTextFieldActionPerformed

    private void wofRenewTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wofRenewTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wofRenewTextFieldActionPerformed

    private void regoRenewTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regoRenewTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regoRenewTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        Hashtable<String,String> data = Utility.readData(updateCarDetailsPanel);
    
                String output= Utility.checkEmptyFields(data);

                if(output.length()!=0)
                {
                    JOptionPane.showMessageDialog(this, output);
                }
                else{
                    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

                    int RegoNumber = Integer.parseInt(regoNumberTextField.getText());
                    String colour = colourTextField.getText();
                    CarTransmission transmission = CarTransmission.valueOf(transmissionComboBox.getSelectedItem().toString());
                    double engineSize = Double.parseDouble(engineSizeTextField.getText());
                    double rentPerDay = Double.parseDouble(rentPerDayTextField.getText());
                    String wofDueString = wofRenewTextField.getText();
                    String regoRenewString = regoRenewTextField.getText();
                    CarStatus status = CarStatus.valueOf(statusComboBox.getSelectedItem().toString());
                    int regoNum = Integer.parseInt(regoNumTextField.getText());
                    int employeeID = 0;
                    employeeID = Integer.parseInt(employeeIDTextField.getText());

                    Date wofRenew = null;
                    Date regoRenew = null;

                    try
                    {
                        wofRenew = df.parse(wofDueString);
                        regoRenew = df.parse(regoRenewString);
                    } catch(ParseException e)
                    {
                    }

                    for(Vehicles v : stock.getStock())
                    {
                        Car car = (Car)v;
                        if(car.getRegoNumber() == RegoNumber)
                        {
                            for(Employee e : stock.getEmployee())
                            {
                                if(e.getPersonID() == employeeID)
                                {
                                    car.setColour(colour);
                                    car.setTransmission(transmission);
                                    car.setEngineSize(engineSize);
                                    car.setRentPerDay(rentPerDay);
                                    car.setWOFdue(wofRenew);
                                    car.setRegoRenew(regoRenew);
                                    car.setStatus(status);
                                    car.setRegoNumber(regoNum);
                                    //Confirm book has been updated in the arraylist
                                    JOptionPane.showMessageDialog(this, "Car Information Updated Successfully");
                                }       
                            }
                        }
                    }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Stock st = MainFrame.stock;
        
        int RegoNumber = Integer.parseInt(regoNumberTextField.getText());
        
        for(Vehicles v : st.getStock())
        {
            Car car = (Car)v;
            if(car.getRegoNumber() == RegoNumber)
            {
                colourTextField.setText(car.getColour());
                transmissionComboBox.getModel().setSelectedItem(car.getTransmission());
                engineSizeTextField.setText(Double.toString(car.getEngineSize()));
                rentPerDayTextField.setText(Double.toString(car.getRentPerDay()));
                statusComboBox.getModel().setSelectedItem(car.getStatus());
                regoNumTextField.setText(Integer.toString(car.getRegoNumber()));

                Date wofRenew = car.getWOFdue();
                Date regoRenew = car.getWOFdue();

                String wofRenewN = new SimpleDateFormat("dd/MM/yyyy").format(wofRenew);
                String regoRenewN = new SimpleDateFormat("dd/MM/yyyy").format(regoRenew);

                wofRenewTextField.setText(wofRenewN);
                regoRenewTextField.setText(regoRenewN);
                    
                JOptionPane.showMessageDialog(this, "Car Found!!!");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void transmissionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmissionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transmissionComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JTextField employeeIDTextField;
    private javax.swing.JLabel engineSizeLabel;
    private javax.swing.JTextField engineSizeTextField;
    private javax.swing.JLabel regoNumLabel;
    private javax.swing.JTextField regoNumTextField;
    private javax.swing.JLabel regoNumberLabel;
    private javax.swing.JTextField regoNumberTextField;
    private javax.swing.JLabel regoRenewLabel;
    private javax.swing.JTextField regoRenewTextField;
    private javax.swing.JLabel rentPerDayLabel;
    private javax.swing.JTextField rentPerDayTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JComboBox<String> transmissionComboBox;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updateCarDetailsPanel;
    private javax.swing.JLabel wofRenewLabel;
    private javax.swing.JTextField wofRenewTextField;
    // End of variables declaration//GEN-END:variables
}
