/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.HumanResource;

import EmployeeAndCustomerManagement.Customer;
import EmployeeAndCustomerManagement.Employee;
import EmployeeAndCustomerManagement.EmployeeRole;
import EmployeeAndCustomerManagement.PersonType;
import GUI.Utility.Utility;
import StockMaintenance.Stock;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import qualitycars.MainFrame;

/**
 *
 * @author rbhaskar
 */
public class UpdateInformationIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateInformationIFrame
     */
    public UpdateInformationIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateInformationPanel = new javax.swing.JPanel();
        employeeIDLabel = new javax.swing.JLabel();
        employeeIDTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        officeAddressLabel = new javax.swing.JLabel();
        officeAddressTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        phoneExtTextField = new javax.swing.JTextField();
        phoneExtLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        passwordTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        updateEmployeeButton = new javax.swing.JButton();
        searchPersonButton = new javax.swing.JButton();
        personTypeLabel = new javax.swing.JLabel();
        personTypeComboBox = new javax.swing.JComboBox<>();
        customerIDLabel = new javax.swing.JLabel();
        customerIDTextField = new javax.swing.JTextField();
        nameTextField1 = new javax.swing.JTextField();
        officeAddressTextField1 = new javax.swing.JTextField();
        addressTextField1 = new javax.swing.JTextField();
        phoneNumberTextField1 = new javax.swing.JTextField();
        phoneExtTextField1 = new javax.swing.JTextField();
        birthdayTextField1 = new javax.swing.JTextField();
        birthdayLabel1 = new javax.swing.JLabel();
        phoneExtLabel1 = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        officeAddressLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        updateEmployeeButton1 = new javax.swing.JButton();

        setClosable(true);

        UpdateInformationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18), new java.awt.Color(0, 204, 51))); // NOI18N

        employeeIDLabel.setText("Employee ID");

        employeeIDTextField.setName("Employee ID"); // NOI18N

        nameLabel.setText("Name");

        nameTextField.setName("Employee Name"); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        officeAddressLabel.setText("Office Address");

        officeAddressTextField.setName("Office Address"); // NOI18N

        addressTextField.setName("Home Address"); // NOI18N

        addressLabel.setText("Home Address");

        phoneNumberLabel.setText("Phone Number");

        phoneNumberTextField.setName("Phone Number"); // NOI18N

        phoneExtTextField.setName("Phone Extension"); // NOI18N

        phoneExtLabel.setText("Phone Extension");

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        roleLabel.setText("Role");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        roleComboBox.setName("Role"); // NOI18N

        passwordTextField.setName("Password"); // NOI18N

        usernameTextField.setName("UserName"); // NOI18N

        updateEmployeeButton.setText("Update Employee Record");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        searchPersonButton.setText("Search Person");
        searchPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPersonButtonActionPerformed(evt);
            }
        });

        personTypeLabel.setText("Person Type");

        personTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Customer" }));
        personTypeComboBox.setName("Person Type"); // NOI18N

        customerIDLabel.setText("Customer ID");

        customerIDTextField.setName("Customer ID"); // NOI18N

        nameTextField1.setName("Cutomer Name"); // NOI18N
        nameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField1ActionPerformed(evt);
            }
        });

        officeAddressTextField1.setName("Address"); // NOI18N

        addressTextField1.setName("License Number"); // NOI18N

        phoneNumberTextField1.setName("License Expiry"); // NOI18N

        phoneExtTextField1.setName("Phone Number"); // NOI18N

        birthdayTextField1.setName("Age"); // NOI18N

        birthdayLabel1.setText("Age");

        phoneExtLabel1.setText("Phone Number");

        phoneNumberLabel1.setText("License Expiry");

        addressLabel1.setText("License Number");

        officeAddressLabel1.setText("Address");

        nameLabel1.setText("Name");

        updateEmployeeButton1.setText("Update Employee Record");
        updateEmployeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateInformationPanelLayout = new javax.swing.GroupLayout(UpdateInformationPanel);
        UpdateInformationPanel.setLayout(UpdateInformationPanelLayout);
        UpdateInformationPanelLayout.setHorizontalGroup(
            UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateInformationPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(employeeIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(personTypeLabel)
                .addGap(18, 18, 18)
                .addComponent(personTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateInformationPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(updateEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateEmployeeButton1)
                .addGap(78, 78, 78))
            .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordTextField)
                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(officeAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneExtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(officeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneExtTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(birthdayLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneExtLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneNumberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(officeAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(officeAddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneNumberTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneExtTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(birthdayTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(searchPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateInformationPanelLayout.setVerticalGroup(
            UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateInformationPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personTypeLabel)
                    .addComponent(personTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(officeAddressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(officeAddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneExtLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneExtTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthdayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdayTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdateInformationPanelLayout.createSequentialGroup()
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(officeAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(officeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneExtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneExtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(UpdateInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateEmployeeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void searchPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPersonButtonActionPerformed
        // TODO add your handling code here:

            Stock st = MainFrame.stock;

            PersonType personType = PersonType.valueOf(personTypeComboBox.getSelectedItem().toString());

            if(personType.equals(PersonType.Employee))
            {
                int employeeID = Integer.parseInt(employeeIDTextField.getText());

                for(Employee e : st.getEmployee())
                {
                    if(e.getPersonID() == employeeID)
                    {
                        nameTextField.setText(e.getName());
                        officeAddressTextField.setText(e.getOfficeAddress());
                        phoneNumberTextField.setText(e.getTelephoneNumber());
                        usernameTextField.setText(e.getUsername());
                        passwordTextField.setText(e.getPassword());
                        roleComboBox.getModel().setSelectedItem(e.getRole());
                        phoneExtTextField.setText(Integer.toString(e.getPhoneExtension()));
                        addressTextField.setText(e.getAddress());


                        JOptionPane.showMessageDialog(this, "Employee Found!!!");
                    }
                }
            } else if(personType.equals(PersonType.Customer))
            {

                int customerID = Integer.parseInt(customerIDTextField.getText());

                for(Customer c : st.getCustomer())
                {
                    if(c.getPersonID() == customerID)
                    {
                        nameTextField1.setText(c.getName());
                        officeAddressTextField1.setText(c.getAddress());
                        addressTextField1.setText(c.getLicenseNumber());
                        phoneExtTextField1.setText(c.getTelephoneNumber());
                        birthdayTextField1.setText(Integer.toString(c.getAge()));

                        Date expiry = c.getLicenseExpiry();
                        String expiryS = new SimpleDateFormat("dd/MM/yyyy").format(expiry);

                        phoneNumberTextField1.setText(expiryS);

                        JOptionPane.showMessageDialog(this, "Customer Found!!!");
                    }
                }
            } else
            {
                JOptionPane.showMessageDialog(this, "No Record for Customer or Employee Found!!!");
            }
    }//GEN-LAST:event_searchPersonButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        // TODO add your handling code here:
            Stock stock = MainFrame.stock;

            PersonType personType = PersonType.valueOf(personTypeComboBox.getSelectedItem().toString());

            //Parse Date
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date licenseExpiry = null;

            if(personType.equals(PersonType.Employee))
            {
                int employeeID = Integer.parseInt(employeeIDTextField.getText());
                String name = nameTextField.getText();
                String officeAddress = officeAddressTextField.getText();
                String phoneNumber = phoneNumberTextField.getText();
                String username = usernameTextField.getText();
                String password = passwordTextField.getText();
                EmployeeRole empRole = EmployeeRole.valueOf(roleComboBox.getSelectedItem().toString());
                int phoneExten = Integer.parseInt(phoneExtTextField.getText());
                String address = addressTextField.getText();


                for(Employee e : stock.getEmployee())
                {
                    if(e.getPersonID() == employeeID)
                    {
                        e.setName(name);
                        e.setOfficeAddress(officeAddress);
                        e.setTelephoneNumber(phoneNumber);
                        e.setUsername(username);
                        e.setPassword(password);
                        e.setPhoneExtension(phoneExten);
                        e.setAddress(address);
                        
                        //Validate so that people can be downgraded but not upgraded
                            if(e.getRole().toString().equals("Admin"))
                            {
                                e.setRole(empRole);
                            }else
                            {
                                JOptionPane.showMessageDialog(this, "Employee cannot be upgraded to Admin. Anyhow, can be downgraded.");
                            }
                        //Confirm Customer has been updated in the arraylist
                        JOptionPane.showMessageDialog(this, "Employee Information Updated Successfully");
                        }       
                }
            }else if(personType.equals(PersonType.Customer))
            {
                int customerID = Integer.parseInt(customerIDTextField.getText());
                String customerName = nameTextField1.getText();
                String customerAddress = officeAddressTextField1.getText();
                String licenseNumber = addressTextField1.getText();
                String licenseExpiryString = phoneNumberTextField1.getText();
                String custPhoneNumber = phoneExtTextField1.getText();
                int age = Integer.parseInt(birthdayTextField1.getText());

                try {
                licenseExpiry = df.parse(licenseExpiryString);
                    } 
                catch (ParseException e) 
                    {
                        e.printStackTrace();
                    }

                for(Customer c : stock.getCustomer())
                {
                    if(c.getPersonID() == customerID)
                    {
                        c.setName(customerName);
                        c.setAge(age);
                        c.setAddress(customerAddress);
                        c.setLicenseNumber(licenseNumber);
                        c.setTelephoneNumber(custPhoneNumber);
                        c.setLicenseExpiry(licenseExpiry);
                        //Confirm Customer has been updated in the arraylist
                        JOptionPane.showMessageDialog(this, "Customer Information Updated Successfully");
                    }
                }
            }
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void nameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField1ActionPerformed

    private void updateEmployeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmployeeButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateInformationPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField addressTextField1;
    private javax.swing.JLabel birthdayLabel1;
    private javax.swing.JTextField birthdayTextField1;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerIDTextField;
    private javax.swing.JLabel employeeIDLabel;
    private javax.swing.JTextField employeeIDTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JLabel officeAddressLabel;
    private javax.swing.JLabel officeAddressLabel1;
    private javax.swing.JTextField officeAddressTextField;
    private javax.swing.JTextField officeAddressTextField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JComboBox<String> personTypeComboBox;
    private javax.swing.JLabel personTypeLabel;
    private javax.swing.JLabel phoneExtLabel;
    private javax.swing.JLabel phoneExtLabel1;
    private javax.swing.JTextField phoneExtTextField;
    private javax.swing.JTextField phoneExtTextField1;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField phoneNumberTextField1;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton searchPersonButton;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JButton updateEmployeeButton1;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
